#!/usr/bin/env bash
# Configures an Ubuntu server as follows:
#   - localhost resolves to 127.0.0.2
#   - facebook.com resolves to 8.8.8.8

grep -v "localhost" /etc/hosts > hosts
echo -e "127.0.0.2\tlocalhost\n8.8.8.8\tfacebook.com" > /etc/hosts
cat hosts >> /etc/hosts
rm -rf hosts
